language: python
addons:
  chrome: stable
jobs:
  include:
    - stage: test-iati-360
      python: "3.5"
      dist: xenial
      install:
        - "git clone 'https://github.com/OpenDataServices/cove.git'"
        - "cd cove"
        - "pip install -r requirements_dev.txt"
        - "pip install -r requirements_iati.txt"
        - "wget https://chromedriver.storage.googleapis.com/2.36/chromedriver_linux64.zip; unzip chromedriver_linux64.zip -d chromedriver; export PATH=$PATH:`pwd`/chromedriver"
      script:
        - "CUSTOM_SERVER_URL=https://dataquality.threesixtygiving.org/ DJANGO_SETTINGS_MODULE=cove_360.settings py.test cove_360/tests_functional.py"
        #- "CUSTOM_SERVER_URL=http://iati.cove.opendataservices.coop/ DJANGO_SETTINGS_MODULE=cove_iati.settings py.test cove_iati/tests_functional.py"
    - stage: test-ocds
      python: "3.6"
      dist: bionic

      install:
        - "git clone 'https://github.com/open-contracting/cove-ocds.git' coveocds"
        - "cd coveocds"
        - "pip install -r requirements_dev.txt"
        - "wget https://chromedriver.storage.googleapis.com/2.36/chromedriver_linux64.zip; unzip chromedriver_linux64.zip -d chromedriver; export PATH=$PATH:`pwd`/chromedriver"
      script:
        - "CUSTOM_SERVER_URL=http://standard.open-contracting.org/ DJANGO_SETTINGS_MODULE=cove_project.settings py.test cove_ocds/tests_functional.py"
